global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dvd-flix'
    metrics_path: '/api/v1/prometheus/metrics/dvd-flix'
    static_configs:
      - targets: ['nginx:80']